version: "1"
steps:
  - name: test
    image: target/vela-kaniko:latest
    pull: always
    secrets: [ kaniko_username, kaniko_password ]
    parameters:
      registry: index.docker.io
      repo: index.docker.io/jayceejr/jumpdai
